// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAb_hWUWfAFh6AnoSM3gyVToaPxAiC-iwo',
    appId: '1:856440743769:web:ab6299962298408c240e48',
    messagingSenderId: '856440743769',
    projectId: 'food-management-1ee0f',
    authDomain: 'food-management-1ee0f.firebaseapp.com',
    storageBucket: 'food-management-1ee0f.firebasestorage.app',
    measurementId: 'G-DNXT4W5QBF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYEsxoUaf_4eW-scTFXgHvdPdPyvY84F4',
    appId: '1:856440743769:android:2c59cc0157b9663e240e48',
    messagingSenderId: '856440743769',
    projectId: 'food-management-1ee0f',
    storageBucket: 'food-management-1ee0f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANjiZhtDVF8gyFi3e_BAjpkrjm9UYgMgk',
    appId: '1:856440743769:ios:492cdd93ca970538240e48',
    messagingSenderId: '856440743769',
    projectId: 'food-management-1ee0f',
    storageBucket: 'food-management-1ee0f.firebasestorage.app',
    iosBundleId: 'com.example.foodProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANjiZhtDVF8gyFi3e_BAjpkrjm9UYgMgk',
    appId: '1:856440743769:ios:492cdd93ca970538240e48',
    messagingSenderId: '856440743769',
    projectId: 'food-management-1ee0f',
    storageBucket: 'food-management-1ee0f.firebasestorage.app',
    iosBundleId: 'com.example.foodProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAb_hWUWfAFh6AnoSM3gyVToaPxAiC-iwo',
    appId: '1:856440743769:web:45d360e3dc221a9c240e48',
    messagingSenderId: '856440743769',
    projectId: 'food-management-1ee0f',
    authDomain: 'food-management-1ee0f.firebaseapp.com',
    storageBucket: 'food-management-1ee0f.firebasestorage.app',
    measurementId: 'G-N6GMLRW6RX',
  );
}
